### ISSUE TITLE
Docker Hub Images

### ISSUE THREAD

**Issue by radarsymphony** [tiredofit/docker-limesurvey#3]
Hi there Tiredofit,

I see you're actively releasing new versions of the packaged limesurvey on Github. However, I just went to https://hub.docker.com/r/tiredofit/limesurvey/tags and it looks like the last limesurvey image was pushed a year ago. I'm just checking in to see if that is intentional or if maybe there's an issue somewhere along the pipeline.

**Comment by tiredofit** [comment]
Looks like Github finally disabled the `set` commands that were in the old pipeline. https://github.com/tiredofit/docker-limesurvey/commit/5073924e079733c69cdc1ac7d99fd82f7fbf8f44 Resolves. 

https://github.com/tiredofit/docker-limesurvey/actions is likely a better place to look to see if build is happening than trying to sift through Docker Hub..
